{% set python_min = "3.10" %}
{% set name = "txl-launcher" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/txl_launcher-{{ version }}.tar.gz
  sha256: 5af381681f9023a24af4d9e559096c9cc84483a166dc9a86b751a863af2c3113

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - txl =0.3.2

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - txl_launcher

about:
  home: https://github.com/davidbrochart/jpterm/blob/main/plugins/launcher
  summary: TXL plugin for a launcher
  dev_url: https://github.com/davidbrochart/jpterm/blob/main/plugins/launcher
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
